#!/bin/bash
set -e

# Download fmt library
mkdir -p fmt
wget -O fmt/fmt.zip https://github.com/fmtlib/fmt/releases/download/8.1.0/fmt-8.1.0.zip
unzip fmt/fmt.zip -d fmt

# Move back to the root directory
cd ..
