#!/bin/bash

git clone https://github.com/SanderMertens/flecs.git

cd flecs

cmake -S . -B build

cmake --build build

cp $HOME/flecs/build/libflecs_static.a /srv/conda/envs/notebook/lib/libflecs_static.a
cp $HOME/flecs/build/libflecs.so /srv/conda/envs/notebook/lib/libflecs.so

cp $HOME/flecs/flecs.h /srv/conda/envs/notebook/include/flecs.h

cd ..
