#!/bin/bash
set -e

# Install vcpkg
git clone https://github.com/microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg integrate install

# Install C++ libraries using vcpkg
./vcpkg install fmt

# Move back to the root directory
cd ..
